"""alter table todo state attribute

Revision ID: 64aa0a4f89fd
Revises: c7897591c47b
Create Date: 2025-01-16 11:52:04.856681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64aa0a4f89fd'
down_revision: Union[str, None] = 'c7897591c47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
