name: Pipeline
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SECURITY_TYPE: ${{ secrets.SECURITY_TYPE }}
      TIME_FOR_EXPIRE_TOKEN: ${{ secrets.TIME_FOR_EXPIRE_TOKEN }}

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3
      
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Executar testes
        run: poetry run task test